name: Deploy to Clever Cloud

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        sparse-checkout: 'plapp'
        sparse-checkout-cone-mode: false
    - name: Move Play app to root # https://github.com/actions/checkout/issues/483#issuecomment-1756354321
      run: |
        ls -lah
        shopt -s dotglob
        mv plapp/* .
        ls -lah
        rm -rf .git
        rm -rf plapp
        ls -lah
        git init
        git config user.email "GitHub.Actions@svpofwfttc.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "moved Play app to root"
    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install the Clever Tools # https://www.clever-cloud.com/doc/reference/clever-tools/getting_started/#via-npm
      run: npm install -g clever-tools
    - name: Link to the Clever Cloud account # https://www.clever-cloud.com/doc/reference/clever-tools/getting_started/#linking-your-account
      run: clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
    - name: Link to the app # https://www.clever-cloud.com/doc/reference/clever-tools/getting_started/#linking-an-existing-application
      run: clever link ${{ secrets.CLEVER_APP_ID }}
    - name: Deploy # https://www.clever-cloud.com/doc/reference/clever-tools/getting_started/#deploying-new-code
      continue-on-error: true
      id: deployNewCode
      run: clever deploy --force
    - name: Restart # if there was no new code
      continue-on-error: true
      if: ${{ steps.deployNewCode.outcome != 'success'}}
      id: restartOldCode
      run: clever restart --without-cache
    - name: Fail # if both Deploy and Restart failed
      if: ${{ steps.deployNewCode.outcome != 'success' && steps.restartOldCode.outcome != 'success' }}
      run: exit 1
