version = 3.11.5
runner.dialect = scala3

# https://scalameta.org/scalafmt/docs/configuration.html#maxcolumn
maxColumn = 120
# https://scalameta.org/scalafmt/docs/configuration.html#lineendings
lineEndings = preserve
