name: Deploy to Clever Cloud

on:
  workflow_run:
    branches: [ main ]
    workflows: ["Scan"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install the Clever Tools # https://www.clever-cloud.com/doc/reference/clever-tools/getting_started/#via-npm
      run: npm install -g clever-tools
    - name: Link to the Clever Cloud account # https://www.clever-cloud.com/doc/reference/clever-tools/getting_started/#linking-your-account
      run: clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
    - name: Link to the app # https://www.clever-cloud.com/doc/reference/clever-tools/getting_started/#linking-an-existing-application
      run: clever link ${{ secrets.CLEVER_APP_ID }}
    - name: Deploy # https://www.clever-cloud.com/doc/reference/clever-tools/getting_started/#deploying-new-code
      continue-on-error: true
      id: deployNewCode
      run: clever deploy
    - name: Restart # if there was no new code
      continue-on-error: true
      if: ${{ steps.deployNewCode.outcome != 'success'}}
      id: restartOldCode
      run: clever restart --without-cache
    - name: Fail # if both Deploy and Restart failed
      if: ${{ steps.deployNewCode.outcome != 'success' && steps.restartOldCode.outcome != 'success' }}
      run: exit 1
