name: Scan

on:
  workflow_run:
    branches: [ main ]
    workflows: ["Test"]
    types: [completed]
  schedule:
    - cron: '0 12 * * 0'

permissions:
  contents: read

concurrency:
  group: scan-${{ github.event.workflow_run.head_branch || 'schedule' }}
  cancel-in-progress: true

jobs:
  Sonar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: back-end and front-end
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        with:
          # https://docs.sonarcloud.io/advanced-setup/analysis-scope/#restrict-the-scope-of-analysis-in-general
          args: >
            -Dsonar.organization=squoss
            -Dsonar.projectKey=Squoss_Twotle
            -Dsonar.sources=beapi/app/,beapi/hexagon/src/main/scala/,fegui/src/
            -Dsonar.tests=beapi/test/,beapi/hexagon/src/test/scala/
#            -Dsonar.exclusions=fegui/src/__tests__/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
  update-graph:
    # https://www.scala-lang.org/blog/2022/07/18/secure-your-dependencies-on-github.html
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: sbt/setup-sbt@bfea3c5f48abd221b04a6df4798aa5eb8b6a2baf # v1.5.6
      - uses: scalacenter/sbt-dependency-submission@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
        with:
          ## Optional: Define the working directory of your build.
          ## It should contain the build.sbt file.
          working-directory: './beapi/'
