name: SonarCloud

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]
  schedule:
    - cron: '0 12 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: back-end and front-end
        uses: sonarsource/sonarcloud-github-action@master
        with:
          # https://docs.sonarcloud.io/advanced-setup/analysis-scope/#restrict-the-scope-of-analysis-in-general
          args: >
            -Dsonar.organization=squoss
            -Dsonar.projectKey=Squoss_Squawg
            -Dsonar.sources=beuawg/app/,beuawg/reinraum/src/main/,feuawg/src/
            -Dsonar.tests=beuawg/test/,beuawg/reinraum/src/test/,feuawg/src/__tests__/
            -Dsonar.exclusions=feuawg/src/__tests__/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
